from tkinter import *
from tkinter import filedialog
from tkinter import ttk
import subprocess ,sys
def show():         
    v1 = float(val1.get())
    v2 = float(val2.get())
    v3 = float(val3.get())
    label.config(text= (v1-(v3-v2)*2))
def exit(): 
    s=label.cget('text')
    with open("erd.txt",'w') as f:
        f.write(str(s))
    subprocess.run(['python3','spcal.py'])
    root.destroy()
root = Tk()
root.title('erd')
root.protocol("WM_DELETE_WINDOW",exit)
frame1 = ttk.LabelFrame(root,text="rim diameter(mm)")
frame1.pack()
frame2 = ttk.LabelFrame(root,text="t(mm)")
frame2.pack()
frame3 = ttk.LabelFrame(root,text="depth(mm)")
frame3.pack()
frame4 = ttk.LabelFrame(root,text="erd(mm)")
frame4.pack()
val1= StringVar()
val1.set('600')
sp1=ttk.Spinbox(frame1,format='%3.1f',textvariable=val1,from_=500,to=700,increment=0.5,command=show)
sp1.pack()
val2 = StringVar()
val2.set('1')
sp2=ttk.Spinbox(frame2,format='%3.1f',state='readonly',textvariable=val2,from_=0,to=2,increment=0.1,command=show)
sp2.pack()
val3 = StringVar()
val3.set('15')
sp3=ttk.Spinbox(frame3,format='%3.1f',state='readonly',textvariable=val3,from_=0,to=30,increment=0.1,command=show)
sp3.pack()
label=ttk.Label(frame4)
label.pack()
show()
root.mainloop()
